### ISSUE TITLE
2 Questions

### ISSUE THREAD

**Issue by SteveDCronin** [Azure-Samples/ms-identity-macOS-swift-objc#10]
1) Why does the title contain 'objc' when in fact the application is entirely in Swift?

2) How can you call the MSGraphEndpoint without a pod & import for 'MSGraphClientSDK'?
   Does MSAL somehow include this access within it?

**Comment by antrix1989** [comment]
Hi @SteveDCronin. Thanks for the questions, see my answers below:
1. MSAL SDK is written in ObjC and this sample shows how to use it in a Swift application.
2. We don't use MSGraphClientSDK in this sample. We are just sending an http request to https://graph.microsoft.com/v1.0/me/ endpoint.
