### ISSUE TITLE
Why does a small change cause a failure?

### ISSUE THREAD

**Issue by SteveDCronin** [Azure-Samples/ms-identity-macOS-swift-objc#11]
The description states that this library allows swift to read MSGraph.
The baseline does NOT import MSGraphSDK and yet makes a call to 'https://graph.microsoft.com/v1.0/me'

So in an attempt to better understand and to verify the validity of the description:
1) I supplied my ClientID 
2) I supplied my redirectURI as stated in the Azure.  
3) I changed kScopes to ["user.read","MailboxSettings.Read"]
4) I changed getGraphEndpoint() to return "v1.0/me/outlook/masterCategories"

When I run the modified app the various prompts for authentication runs as expected  - BUT
Result from Graph: {
    error =     {
        code = AuthenticationError;
        innerError =         {
            date = "2020-06-11T18:51:33";
            "request-id" = "804cf5a5-ec1b-402e-8037-ea020f78a0d4";
        };
        message = "Error authenticating with resource";
    };
})

Please clarify what I have failed to understand!

**Comment by antrix1989** [comment]
Could you please provide us logs with correlation id. See here how to collect [them](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-logging?tabs=dotnet#logging-in-msal-for-ios-and-macos).
