### ISSUE TITLE
Few questions regarding Microsoft login

### ISSUE THREAD

**Issue by jis248** [Azure-Samples/ms-identity-macOS-swift-objc#12]
1. On click of Microsoft button, I get this message "<MyApp> wants to use “microsoftonline.com” to sign in." and on continue it redirects me to safari browser to login. So far no issue but on VM this message does not show up and nothing happens on Microsoft button. No issue with permission in VM

2.How to clear session and tokens on that same button if it has session and token of previous account.

**Comment by juan-arias** [comment]
Hi @jis248, thank you for reporting this. MSAL uses ASWebAuthenticationSession for this scenario on macOS. Could you please file a radar with Apple with appropriate logs to investigate.

**Comment by jis248** [comment]
yes, sent them logs and waiting for reply now

**Comment by ameyapat** [comment]
@jis248 Is the VM the same version as your physical device? Is this for a B2C Account?

**Comment by jis248** [comment]
VM has informed it is from their side location and few admin access is not working. So we in the process of  changing VM provider
