### ISSUE TITLE
Browser doesn't open

### ISSUE THREAD

**Issue by razvanrujoiu** [Azure-Samples/ms-identity-macOS-swift-objc#13]
After the alert: “MSALMacOS” wants to use “microsoftonline.com” to sign in." and i press continue, i expect the safari browser to automatically open and continue the login process but instead nothing happens after pressing continue.

```
TID=5176321 MSAL 1.1.26 Mac 12.1.0 [2022-02-03 17:48:57 - 53D242BA-7AEF-43CC-87E2-FDEF1149B1D2] [MSAL] Resolved authority, validated: YES, error: 0
TID=5175490 MSAL 1.1.26 Mac 12.1.0 [2022-02-03 17:48:57 - 53D242BA-7AEF-43CC-87E2-FDEF1149B1D2] [MSAL] Start webview authorization session with webview controller class MSIDSystemWebviewController: 
```

**Comment by juan-arias** [comment]
Hi @razvanrujoiu, thank you for reporting this. MSAL uses ASWebAuthenticationSession for this scenario on macOS. Could you please file a radar with Apple with appropriate logs to investigate.

**Comment by ameyapat** [comment]
Closing this for now. Please feel free to re-open if issue is related to MSAL
